export const BANNER_INFO = [
  {
    id: 1,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#CCD5AE',
    bannerTitle: '첫 회원가입시 100,000포인트 증정!',
    bannerText: '파격적인 서비스로 저희의 향을 체험해 보세요',
  },
  {
    id: 2,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#E9EDC9',
    bannerTitle: '신규 회원 맞춤형 휴식 라이프 찾기',
    bannerText: '지금 저희의 가족이 되고 회원님 만의 휴식생활을 찾으세요',
  },
  {
    id: 3,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#FEFAE0',
    bannerTitle: '선선한 밤공기에 느낌있는 휴식',
    bannerText: '인센스 휴식 라이프를 위한 인센스',
  },
  {
    id: 4,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#FAEDCD',
    bannerTitle: '식센스 스틱 라벤다향',
    bannerText: '식센스 인센스 Best Product',
  },
  {
    id: 5,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#F6F1F1',
    bannerTitle: '식센스 콘 레인포레스트향',
    bannerText: '저희의 일원이 되어서 인센스 휴식을 즐겨보세요',
  },
];

// export const MAIN_PRODUCT = [
//   {
//     id: 1,
//     productId: 1,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '오이뮤 무화과향',
//     productPrice: 16000,
//     productDiscountRate: 0,
//   },
//   {
//     id: 2,
//     productId: 2,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '오이뮤 백단나무향',
//     productPrice: 16000,
//     productDiscountRate: 0.25,
//   },
//   {
//     id: 3,
//     productId: 3,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '오이뮤 개암향',
//     productPrice: 15000,
//     productDiscountRate: 0,
//   },
//   {
//     id: 4,
//     productId: 4,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '오이뮤 춘계향',
//     productPrice: 16000,
//     productDiscountRate: 0,
//   },
//   {
//     id: 5,
//     productId: 10,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '오이뮤 하계',
//     productPrice: 16000,
//     productDiscountRate: 0,
//   },
//   {
//     id: 6,
//     productId: 11,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '백플로우 인센스 콘',
//     productPrice: 6800,
//     productDiscountRate: 0.3,
//   },
//   {
//     id: 7,
//     productId: 12,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: 'HEM 인센스 콘',
//     productPrice: 2000,
//     productDiscountRate: 0,
//   },
//   {
//     id: 8,
//     productId: 13,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '아포테케 프라그란스',
//     productPrice: 12000,
//     productDiscountRate: 0,
//   },
//   {
//     id: 9,
//     productId: 14,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '어떤 어떤 향',
//     productPrice: 7500,
//     productDiscountRate: 0.25,
//   },
//   {
//     id: 10,
//     productId: 15,
//     productImage: ['/images/insense_2.jpeg', '/images/incense_5.JPG'],
//     productName: '무슨 무슨 향',
//     productPrice: 11000,
//     productDiscountRate: 0,
//   },
// ];
