export const BANNER_INFO = [
  {
    id: 1,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#CCD5AE',
    bannerTitle: '첫 번째 배너 타이틀',
    bannerText: '첫 번째의 소개글',
  },
  {
    id: 2,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#E9EDC9',
    bannerTitle: '두 번째 배너 타이틀',
    bannerText: '두 번째의 소개글',
  },
  {
    id: 3,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#FEFAE0',
    bannerTitle: '세 번째 배너 타이틀',
    bannerText: '세 번째의 소개글',
  },
  {
    id: 4,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#FAEDCD',
    bannerTitle: '네 번째 배너 타이틀',
    bannerText: '네 번째의 소개글',
  },
  {
    id: 5,
    bannerImg: '/images/insense_3.jpeg',
    bannerBackgroundColor: '#F6F1F1',
    bannerTitle: '다섯 번째 배너 타이틀',
    bannerText: '다섯 번째의 소개글',
  },
];

export const MAIN_PRODUCT = [
  {
    id: 1,
    productImage: '/images/insense_2.jpeg',
    productName: '오이뮤 무화과향',
    productPrice: 16000,
    discountRate: 0,
  },
  {
    id: 2,
    productImage: '/images/insense_2.jpeg',
    productName: '오이뮤 백단나무향',
    productPrice: 16000,
    discountRate: 0.25,
  },
  {
    id: 3,
    productImage: '/images/insense_2.jpeg',
    productName: '오이뮤 개암향',
    productPrice: 15000,
    discountRate: 0,
  },
  {
    id: 4,
    productImage: '/images/insense_2.jpeg',
    productName: '오이뮤 춘계향',
    productPrice: 16000,
    discountRate: 0,
  },
  {
    id: 5,
    productImage: '/images/insense_2.jpeg',
    productName: '오이뮤 하계',
    productPrice: 16000,
    discountRate: 0,
  },
  {
    id: 6,
    productImage: '/images/insense_2.jpeg',
    productName: '백플로우 인센스 콘',
    productPrice: 6800,
    discountRate: 0.3,
  },
  {
    id: 7,
    productImage: '/images/insense_2.jpeg',
    bannerTitle: 'HEM 인센스 콘',
    productPrice: 2000,
    discountRate: 0,
  },
  {
    id: 8,
    productImage: '/images/insense_2.jpeg',
    productName: '아포테케 프라그란스',
    productPrice: 12000,
    discountRate: 0,
  },
  {
    id: 9,
    productImage: '/images/insense_2.jpeg',
    productName: '어떤 어떤 향',
    productPrice: 7500,
    discountRate: 0.25,
  },
  {
    id: 10,
    productImage: '/images/insense_2.jpeg',
    productName: '무슨 무슨 향',
    productPrice: 11000,
    discountRate: 0,
  },
];
